services:
  db:
    image: postgres:15-alpine
    container_name: tot_db
    restart: always
    environment:
      POSTGRES_USER: tot_user
      POSTGRES_PASSWORD: tot_password
      POSTGRES_DB: tot_database
    ports:
      - "5432:5432"
    volumes:
      - tot_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tot.ao
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  tot_postgres_data:
